### PR TITLE
Introduce CI

### PR DESCRIPTION
**Pull request by szepeviktor**
https://github.com/szepeviktor/woo-solo-api-test-action/runs/1070141127?check_suite_focus=true 👀

### CODE REVIEW

**Comment by dingo-d** [comment]
Thanks, never bothered to add actions for the docker action (I'm not happy how slow it is - it takes over 5 minutes to run tests on the plugin using GH Actions, whereas it takes 5 seconds locally).

**Comment by szepeviktor** [comment]
> it takes over 5 minutes to run tests on the plugin using GH Actions, whereas it takes 5 seconds locally

@dingo-d The main cause is the lack of npm and composer caching.

If you would like I could make improvements to reach the 5 seconds territory.

**Comment by dingo-d** [comment]
Sure thing, go ahead. But I don't think it's due to composer and npm caching. Since I'm running the tests in the docker, it takes a long time for GH action to fetch and build it, then they need to run...

I tried using the local system provided by actions, but I had issues with connecting to the database.

**Comment by szepeviktor** [comment]
> it takes a long time for GH action to fetch and build it

Nooooooooooooooooooooooooooooooooooooooo!!
GH actions should not build the image.

kép

https://github.com/dingo-d/woo-solo-api/runs/746987724

GH actions only runs the image thus executing `ENTRYPOINT ["/entrypoint.sh"]`

**Comment by dingo-d** [comment]
If you look at that run, it took GH 1min and 11 sec to build a container for the action that runs the tests, and then 3min and 4 seconds to run the actual tests (because it builds the plugin - npm install is huge mostly).

The tests themselves took 3.39sec to run, so ok that part is fine, but the overall process is too long for CI/CD pipeline - for running an integration test that is. I'd expect a long running time for acceptance tests.

**Comment by szepeviktor** [comment]
GH actions may build your images every time because they are not published: https://github.com/marketplace?query=dingo-d

**Comment by szepeviktor** [comment]
kép

https://github.com/abraham/twitteroauth/actions/runs/239369764

3 PHP versions in 53 seconds.

**Comment by dingo-d** [comment]
They are running npm tests, I'm running WordPress integration tests using Codeception. I've tried setting them up on PHP, but, as mentioned, I couldn't connect to the DB on the host machine, and without that, I couldn't run tests.

**Pull request merged**
